# Generated by Django 3.2 on 2023-03-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MadLib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(max_length=100)),
                ('input_words', models.CharField(max_length=500)),
                ('completed_story', models.TextField()),
            ],
        ),
    ]
