# Generated by Django 3.2 on 2023-03-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madLibs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='madlib',
            old_name='completed_story',
            new_name='story',
        ),
        migrations.RemoveField(
            model_name='madlib',
            name='input_words',
        ),
        migrations.RemoveField(
            model_name='madlib',
            name='template',
        ),
        migrations.AddField(
            model_name='madlib',
            name='adjective1',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='madlib',
            name='adjective2',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='madlib',
            name='adverb1',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='madlib',
            name='noun1',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='madlib',
            name='noun2',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='madlib',
            name='place1',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='madlib',
            name='verb1',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
