# Generated by Django 3.2 on 2023-03-07 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madLibs', '0002_auto_20230307_0016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='madlib',
            old_name='adverb1',
            new_name='verb2',
        ),
    ]
