# Generated by Django 3.2 on 2023-03-07 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madLibs', '0003_rename_adverb1_madlib_verb2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='madlib',
            name='story',
        ),
    ]
