# Generated by Django 3.2 on 2023-03-07 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madLibs', '0005_madlib_story'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='madlib',
            name='story',
        ),
    ]
