# Generated by Django 3.2 on 2023-03-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madLibs', '0006_remove_madlib_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='madlib',
            name='story',
            field=models.TextField(default='Hi there people!'),
        ),
    ]
